### ISSUE TITLE
不安定なテストを修正する

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/hr-dash#468]
# 概要
落ちたり通ったり不安定なので直す。

# 再現・確認手順（任意）
* MonthlyReportsController#show については、たぶん `target_month: report.target_month.next_month` が登録できない月になってるのではないかと思う。
* PasswordResetsController#create については不明なので要調査

```
1) MonthlyReportsController#show GET /monthly_reports/:id 
     Failure/Error: let!(:next) { create(:monthly_report, :wip, user: user, target_month: report.target_month.next_month) }

     ActiveRecord::RecordInvalid:
       バリデーションに失敗しました 対象月 must included by user.report_registrable_months
     # ./spec/features/monthly_report_spec.rb:60:in `block (3 levels) in <top (required)>'

  2) PasswordResetsController#create request by valid user 
     Failure/Error: click_on 'Submit'

     Capybara::ElementNotFound:
       Unable to find link or button "Submit"
     # ./spec/features/password_reset_spec.rb:9:in `block (3 levels) in <top (required)>'
```
# ToDo

- [x] ラベル付け

**Comment by bakunyo** [comment]
https://github.com/hr-dash/hr-dash/pull/464/commits/5eddcc4632095a5441521dc88f3cc04f81a97849
さり気なくここでFixしたので、Closeします
